server:
  port: 8080

spring:
  application:
    name: spring-mybatis
  jpa:
    open-in-view: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql:://@10.253.96.66:3306/cjwl_wms_dev
    url: jdbc:mysql://@10.253.96.66:3306/cjwl_wms_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useAffectedRows=true&allowMultiQueries=true
    #url: jdbc:oracle:thin:@10.8.199.144:1521/intdbnew
    username: root
    password: CjK1rry1as

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.learn.springmybatis.mapper
  mapper-locations: classpath:mappers/*.xml


logging:
  level:
    com.learn.springmybatis.mapper: debug
    com.learn.springmybatis.shenzhen.mapper: debug





